/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The API process is running */
        get: operations["live_api_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Database and job engine are reachable */
        get: operations["ready_api_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version, services, workers and hardware */
        get: operations["system_status_api_system_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent jobs, newest first */
        get: operations["recent_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One job */
        get: operations["one_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/self-test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run the system self-test (CPU and GPU workers) */
        post: operations["start_self_test_api_jobs_self_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask a running job to stop */
        post: operations["cancel_job_api_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Edit operations, export formats and upload limits */
        get: operations["ops_catalog_api_ops_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Images in the library, newest first */
        get: operations["list_assets_api_assets_get"];
        put?: never;
        /**
         * Upload an image (raw request body)
         * @description Send the file bytes as the request body and its name in `filename`. The body is streamed to disk and hashed, never held in memory. Uploading a file that is already in the library returns the existing image with `duplicate: true` and status 200.
         */
        post: operations["upload_asset_api_assets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One image */
        get: operations["one_asset_api_assets__asset_id__get"];
        put?: never;
        post?: never;
        /** Delete an image and its files */
        delete: operations["delete_asset_api_assets__asset_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{asset_id}/thumb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 320 px thumbnail (WebP) */
        get: operations["asset_thumb_api_assets__asset_id__thumb_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{asset_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 2048 px preview (WebP) */
        get: operations["asset_preview_api_assets__asset_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{asset_id}/dz/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Deep-zoom pyramid files */
        get: operations["asset_deep_zoom_api_assets__asset_id__dz__path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{asset_id}/original": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download the original file */
        get: operations["asset_original_api_assets__asset_id__original_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{asset_id}/edits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The image's edit document */
        get: operations["get_edits_api_assets__asset_id__edits_get"];
        /** Replace the image's edit document */
        put: operations["put_edits_api_assets__asset_id__edits_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{asset_id}/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Render the current edits at full resolution and encode them */
        post: operations["start_export_api_assets__asset_id__exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{asset_id}/renditions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Exports of this image */
        get: operations["list_renditions_api_assets__asset_id__renditions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/renditions/{rendition_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download an export */
        get: operations["download_rendition_api_renditions__rendition_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/renditions/{rendition_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an export */
        delete: operations["delete_rendition_api_renditions__rendition_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The model catalog and what is installed */
        get: operations["list_models_api_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/{model_id}/install": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Download, verify and install a model
         * @description Idempotent: an installed model returns with `job: null`; a download in progress returns its job.
         */
        post: operations["install_model_api_models__model_id__install_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a model's downloaded files */
        delete: operations["remove_model_api_models__model_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** What a run would produce, and how it would run */
        post: operations["plan_api_ai_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run a model on an image; the result becomes a new image */
        post: operations["start_run_api_ai_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/updates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Running version, newer releases and their notes */
        get: operations["update_status_api_updates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AiPlanOut */
        AiPlanOut: {
            /** Model Id */
            model_id: string;
            /**
             * Task
             * @enum {string}
             */
            task: "upscale" | "denoise" | "background" | "face";
            /** Scale */
            scale: number;
            /**
             * Device
             * @enum {string}
             */
            device: "cuda" | "cpu";
            /** Device Name */
            device_name: string;
            /** Input Width */
            input_width: number;
            /** Input Height */
            input_height: number;
            /** Output Width */
            output_width: number;
            /** Output Height */
            output_height: number;
            /** Output Megapixels */
            output_megapixels: number;
            /** Bit Depth */
            bit_depth: number;
            /** Has Alpha */
            has_alpha: boolean;
            /** Tile */
            tile: number | null;
            /** Batch */
            batch: number | null;
            /** Tiles */
            tiles: number;
            /**
             * Calibrated
             * @description True when the tile size comes from memory measured on this GPU.
             */
            calibrated: boolean;
            /** Estimated Memory Bytes */
            estimated_memory_bytes: number | null;
            /** Disk Bytes */
            disk_bytes: number;
            /** Restore Faces */
            restore_faces: boolean;
            /** Warnings */
            warnings: string[];
        };
        /** AiRunIn */
        AiRunIn: {
            /** Asset Id */
            asset_id: string;
            /** Model Id */
            model_id: string;
            /**
             * Device
             * @description `cpu` forces the CPU even with a GPU.
             * @default auto
             * @enum {string}
             */
            device: "auto" | "cpu";
            /**
             * Restore Faces
             * @description After upscaling, restore faces with GFPGAN (it must be installed).
             * @default false
             */
            restore_faces: boolean;
        };
        /** AiRunStartOut */
        AiRunStartOut: {
            job: components["schemas"]["JobOut"];
            plan: components["schemas"]["AiPlanOut"];
        };
        /** AssetOut */
        AssetOut: {
            /** Id */
            id: string;
            /** Original Name */
            original_name: string;
            /** Format */
            format: string;
            /**
             * Width
             * @description Width after EXIF orientation.
             */
            width: number;
            /** Height */
            height: number;
            /** Bit Depth */
            bit_depth: number;
            /** Has Alpha */
            has_alpha: boolean;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Status
             * @enum {string}
             */
            status: "processing" | "ready" | "failed";
            /** Error */
            error: {
                [key: string]: unknown;
            } | null;
            /** Exif */
            exif: {
                [key: string]: unknown;
            };
            /** Has Gps */
            has_gps: boolean;
            /** Preview Width */
            preview_width: number | null;
            /** Preview Height */
            preview_height: number | null;
            /** Edits */
            edits?: {
                [key: string]: unknown;
            };
            /** Created At */
            created_at: string | null;
            /** Thumb Url */
            thumb_url: string | null;
            /** Preview Url */
            preview_url: string | null;
            /** Dzi Url */
            dzi_url: string | null;
            /** Original Url */
            original_url: string;
            /**
             * Parent Id
             * @description The image this one was made from by an AI run.
             */
            parent_id?: string | null;
            /**
             * Derivation
             * @description How an AI result was made.
             */
            derivation?: {
                [key: string]: unknown;
            } | null;
        };
        /** CatalogOut */
        CatalogOut: {
            /** Ops */
            ops: components["schemas"]["OpOut"][];
            /** Formats */
            formats: components["schemas"]["OutputFormatOut"][];
            /** Max Input Megapixels */
            max_input_megapixels: number;
            /** Max Upload Mb */
            max_upload_mb: number;
            /** Accepted Extensions */
            accepted_extensions: string;
        };
        /** CropIn */
        CropIn: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** W */
            w: number;
            /** H */
            h: number;
        };
        /**
         * EditDocumentIn
         * @description Validated against the operation catalog on save; see GET /api/ops.
         */
        EditDocumentIn: {
            /**
             * Version
             * @default 1
             * @constant
             */
            version: 1;
            geometry?: components["schemas"]["GeometryIn"];
            /** Ops */
            ops?: components["schemas"]["OpEntryIn"][];
        };
        /** ExportIn */
        ExportIn: {
            /**
             * Format
             * @default jpeg
             * @enum {string}
             */
            format: "jpeg" | "png" | "webp" | "avif" | "tiff";
            /**
             * Quality
             * @default 90
             */
            quality: number;
            /** Max Side */
            max_side?: number | null;
            /** Target Kb */
            target_kb?: number | null;
            /**
             * Strip Metadata
             * @default true
             */
            strip_metadata: boolean;
        };
        /** ExportStartOut */
        ExportStartOut: {
            job: components["schemas"]["JobOut"];
            rendition: components["schemas"]["RenditionOut"];
        };
        /** GeometryIn */
        GeometryIn: {
            /**
             * Rotate
             * @default 0
             * @enum {integer}
             */
            rotate: 0 | 90 | 180 | 270;
            /**
             * Flip H
             * @default false
             */
            flip_h: boolean;
            /**
             * Flip V
             * @default false
             */
            flip_v: boolean;
            crop?: components["schemas"]["CropIn"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * Checks
             * @default {}
             */
            checks: {
                [key: string]: boolean;
            };
        };
        /** JobOut */
        JobOut: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Title */
            title: string;
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "running" | "succeeded" | "failed" | "cancelled";
            /** Progress */
            progress: number;
            /** Message */
            message: string;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error: {
                [key: string]: unknown;
            } | null;
            /** Created At */
            created_at: string | null;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /** ModelInstallOut */
        ModelInstallOut: {
            model: components["schemas"]["ModelOut"];
            /** @description The download job; null when the model was already installed. */
            job: components["schemas"]["JobOut"] | null;
        };
        /** ModelOut */
        ModelOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Task
             * @enum {string}
             */
            task: "upscale" | "denoise" | "background" | "face";
            /** Task Label */
            task_label: string;
            /** Arch */
            arch: string;
            /** Scale */
            scale: number;
            /** Summary */
            summary: string;
            /** License */
            license: string;
            /** License Url */
            license_url: string;
            /** Homepage */
            homepage: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Channels
             * @enum {string}
             */
            channels: "rgb" | "y";
            /**
             * Speed
             * @enum {string}
             */
            speed: "fast" | "balanced" | "slow";
            /** Recommended */
            recommended: boolean;
            /** Tags */
            tags: string[];
            /**
             * Status
             * @enum {string}
             */
            status: "available" | "downloading" | "installed" | "failed";
            /** Job Id */
            job_id: string | null;
            /** Error */
            error: {
                [key: string]: unknown;
            } | null;
            /** Installed At */
            installed_at: string | null;
            /** Runs */
            runs: number;
            /**
             * Calibrated
             * @description Devices this model has measured its memory use on.
             */
            calibrated: string[];
        };
        /** OpEntryIn */
        OpEntryIn: {
            /** Id */
            id: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Params */
            params?: {
                [key: string]: number;
            };
        };
        /** OpOut */
        OpOut: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Group
             * @enum {string}
             */
            group: "light" | "color" | "detail" | "effects";
            /** Description */
            description: string;
            /** Params */
            params: components["schemas"]["OpParamOut"][];
        };
        /** OpParamOut */
        OpParamOut: {
            /** Name */
            name: string;
            /** Label */
            label: string;
            /** Min */
            min: number;
            /** Max */
            max: number;
            /** Step */
            step: number;
            /** Default */
            default: number;
            /** Unit */
            unit: string;
        };
        /** OutputFormatOut */
        OutputFormatOut: {
            /**
             * Id
             * @enum {string}
             */
            id: "jpeg" | "png" | "webp" | "avif" | "tiff";
            /** Label */
            label: string;
            /** Extension */
            extension: string;
            /** Max Side */
            max_side: number;
            /** Lossy */
            lossy: boolean;
            /** Alpha */
            alpha: boolean;
            /** Sixteen Bit */
            sixteen_bit: boolean;
        };
        /** ReleaseOut */
        ReleaseOut: {
            /** Tag */
            tag: string;
            /** Version */
            version: string;
            /** Name */
            name: string;
            /**
             * Notes
             * @description Release notes in GitHub-flavoured Markdown.
             */
            notes: string;
            /** Url */
            url: string;
            /** Published At */
            published_at: string | null;
            /** Prerelease */
            prerelease: boolean;
        };
        /** RenditionOut */
        RenditionOut: {
            /** Id */
            id: string;
            /** Asset Id */
            asset_id: string;
            /** Job Id */
            job_id: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "ready" | "failed";
            /** Format */
            format: string;
            /** Filename */
            filename: string;
            /** Options */
            options: {
                [key: string]: unknown;
            };
            /** Width */
            width: number | null;
            /** Height */
            height: number | null;
            /** Size Bytes */
            size_bytes: number | null;
            /** Quality */
            quality: number | null;
            /** Created At */
            created_at: string | null;
            /** Download Url */
            download_url: string | null;
        };
        /** ServicesOut */
        ServicesOut: {
            /** Database */
            database: boolean;
            /** Temporal */
            temporal: boolean;
            /** Events */
            events: boolean;
        };
        /** SystemOut */
        SystemOut: {
            /** Version */
            version: string;
            /** Environment */
            environment: string;
            services: components["schemas"]["ServicesOut"];
            /** Api */
            api: {
                [key: string]: unknown;
            };
            /** Workers */
            workers: components["schemas"]["WorkerOut"][];
        };
        /** UpdateStatusOut */
        UpdateStatusOut: {
            /** Current Version */
            current_version: string;
            /** Latest Version */
            latest_version: string | null;
            /** Update Available */
            update_available: boolean;
            /**
             * Newer
             * @description Releases newer than the running version, newest first.
             */
            newer: components["schemas"]["ReleaseOut"][];
            /** @description Release notes for the running version, if published. */
            current: components["schemas"]["ReleaseOut"] | null;
            /** Checked At */
            checked_at: string | null;
            /** Error */
            error: string | null;
            /** Repo Url */
            repo_url: string;
            /** Releases Url */
            releases_url: string;
        };
        /** UploadOut */
        UploadOut: {
            asset: components["schemas"]["AssetOut"];
            /**
             * Duplicate
             * @description True when this exact file was already in the library.
             */
            duplicate: boolean;
            job: components["schemas"]["JobOut"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkerOut */
        WorkerOut: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "cpu" | "gpu";
            /** Hostname */
            hostname: string;
            /** Version */
            version: string;
            /** Online */
            online: boolean;
            /**
             * Last Seen
             * Format: date-time
             */
            last_seen: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Info */
            info: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live_api_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    ready_api_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    system_status_api_system_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemOut"];
                };
            };
        };
    };
    recent_jobs_api_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    one_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_self_test_api_jobs_self_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
        };
    };
    cancel_job_api_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ops_catalog_api_ops_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogOut"];
                };
            };
        };
    };
    list_assets_api_assets_get: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Only images made from this one by AI runs. */
                parent_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_asset_api_assets_post: {
        parameters: {
            query: {
                filename: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": unknown;
            };
        };
        responses: {
            /** @description Already in the library */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadOut"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    one_asset_api_assets__asset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_asset_api_assets__asset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    asset_thumb_api_assets__asset_id__thumb_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    asset_preview_api_assets__asset_id__preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    asset_deep_zoom_api_assets__asset_id__dz__path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    asset_original_api_assets__asset_id__original_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_edits_api_assets__asset_id__edits_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditDocumentIn"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_edits_api_assets__asset_id__edits_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditDocumentIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditDocumentIn"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_export_api_assets__asset_id__exports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportStartOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_renditions_api_assets__asset_id__renditions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenditionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_rendition_api_renditions__rendition_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rendition_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_rendition_api_renditions__rendition_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rendition_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelOut"][];
                };
            };
        };
    };
    install_model_api_models__model_id__install_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelInstallOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_model_api_models__model_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_api_ai_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiRunIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiPlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_api_ai_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiRunIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiRunStartOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_status_api_updates_get: {
        parameters: {
            query?: {
                /** @description Ask GitHub now instead of using the cached list. */
                refresh?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
