"""Turn a checked Forge graph into a standalone PyTorch file.

The file contains the block modules (copied from ``siqe/ai/archs/forge_blocks.py``) and one
network class whose attributes are named after the blocks, exactly like the trainer's
``GraphNet``. A checkpoint from Forge therefore loads into it with ``load_state_dict``.
Nothing here imports torch, so the API can show the code.
"""

import re
from pathlib import Path
from typing import Any

from siqe.forge.graph import Analysis

BLOCKS_FILE = Path(__file__).resolve().parent.parent / "ai" / "archs" / "forge_blocks.py"
MARKER = "# --- forge blocks ---"


def class_name(name: str) -> str:
    words = re.findall(r"[A-Za-z0-9]+", name)
    text = "".join(w[:1].upper() + w[1:] for w in words) or "ForgeModel"
    return text if text[0].isalpha() else f"Model{text}"


def constructor(step: dict[str, Any]) -> str | None:
    """The Python expression that builds a step's module, or None for tensor operations."""
    a, t = step["args"], step["type"]
    if t == "conv":
        return f'ConvAct({a["cin"]}, {a["cout"]}, {a["kernel"]}, "{a["act"]}")'
    if t == "down":
        return f'ConvAct({a["cin"]}, {a["cout"]}, 3, "{a["act"]}", stride=2)'
    if t == "up":
        return f'UpConv({a["cin"]}, {a["cout"]}, "{a["act"]}")'
    if t == "activation":
        return f'make_act("{a["act"]}", {a["channels"]})'
    if t == "norm":
        return f'Norm("{a["kind"]}", {a["channels"]})'
    if t == "dropout":
        return f"nn.Dropout2d({a['p']})"
    if t == "res":
        return f"ResGroup({a['channels']}, {a['blocks']}, {a['res_scale']})"
    if t == "rdb":
        return f"DenseBlock({a['cin']}, {a['channels']}, {a['layers']})"
    if t == "attention":
        return f"ChannelAttention({a['channels']}, {a['reduction']})"
    if t == "d2s":
        return f"nn.PixelShuffle({a['factor']})"
    if t == "upsample":
        return f'Resize({a["factor"]}, "{a["mode"]}")'
    return None


def _blocks_source() -> str:
    text = BLOCKS_FILE.read_text(encoding="utf-8")
    return text.split(MARKER, 1)[1].strip("\n")


def generate(name: str, analysis: Analysis) -> str:
    if analysis.problems or not analysis.plan:
        lines = [f"# {name} can't be turned into code yet. Fix these first:"]
        lines += [f"#  - {p.message}" for p in analysis.problems] or ["#  - The graph is empty"]
        return "\n".join(lines) + "\n"
    stats = analysis.stats
    cls = class_name(name)
    init: list[str] = []
    forward: list[str] = []
    result = "x"
    for step in analysis.plan:
        var, ins = step["name"], step["inputs"]
        expr = constructor(step)
        if expr is not None:
            init.append(f"        self.{var} = {expr}")
            forward.append(f"        {var} = self.{var}({ins[0]})")
        elif step["type"] == "input":
            forward.append(f"        {var} = x")
        elif step["type"] == "add":
            forward.append(f"        {var} = {' + '.join(ins)}")
        elif step["type"] == "concat":
            forward.append(f"        {var} = torch.cat([{', '.join(ins)}], 1)")
        elif step["type"] == "output":
            result = ins[0]
    channels = "brightness (Y)" if stats.color == "y" else "RGB"
    header = f'''"""{cls}: generated by SIQE Studio Forge.

Input: {channels}, values 0 to 1, shape (batch, {1 if stats.color == "y" else 3}, height, width).
Output: the same channels at ×{stats.scale}. {stats.params:,} parameters,
{stats.gmacs_per_megapixel} GMACs per input megapixel.

Load a Forge checkpoint with:
    model = {cls}()
    model.load_state_dict(safetensors.torch.load_file("model.safetensors"))
"""

import torch
from torch import nn
from torch.nn import functional as F

'''
    network = [
        "",
        "",
        f"class {cls}(nn.Module):",
        f"    scale = {stats.scale}",
        f"    in_channels = {1 if stats.color == 'y' else 3}",
        "",
        "    def __init__(self) -> None:",
        "        super().__init__()",
        *(init or ["        pass"]),
        "",
        "    def forward(self, x: torch.Tensor) -> torch.Tensor:",
        *forward,
        f"        return {result}",
        "",
    ]
    return header + _blocks_source() + "\n" + "\n".join(network)
